name: dropwizard-continuous-integration

on:
  push:
    branch:
      - main


jobs:
  build-and-test:
    runs-on: ubuntu/latest
    steps:
      - uses: actions/checkout@v1 # checking out code into a machine

      - name: Setup Java # to install Java on the new machine
        uses: action/setup-java@v1
        with:
          java-version: 11

      - name: Gradle Build # run the build
        working-directory: . # run this at the top level
        run: ./gradlew build -x test # only run the build, don't run the tests

      - name: Test using Gradle # test
        working-directory: . # run this at the top level
        run: ./gradlew test

  system-test:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - uses: actions/checkout@v1

      - name: run the server
      working-directory: .
      run: |
      chmod +x gradlew
      docker-compose up --build -d

      - name: setup python
        uses: action/setup-python@v1
        with:
          python-version: '3.7'

      - run: pip install pytest requests

      - name: run system test
        working-directory: .
        run: pytest

      - name: stop containers
        working-directory: .
        run: docker-compose down
      
